
import { TextLayer, Template } from './types';

// Default Layers Structure
export const INITIAL_LAYERS: TextLayer[] = [
  {
    id: 'header',
    name: 'Header Text',
    type: 'text',
    text: 'Restoration Expert',
    enabled: true,
    x: 193,
    y: 97,
    align: 'left',
    fontFamily: 'SF Pro Display',
    fontSize: 16,
    fontWeight: '900',
    color: '#000000',
    letterSpacing: 0,
    lineHeight: 1.2,
    textTransform: 'uppercase',
    shadow: false,
    shadowColor: 'rgba(0,0,0,0.5)',
    shadowBlur: 0,
    gradient: { enabled: false, startColor: '#ffffff', endColor: '#cccccc', type: 'vertical' },
    stroke: { enabled: false, color: '#000000', width: 1 },
    isDynamic: false
  },
  {
    id: 'member-name',
    name: 'Member Name',
    type: 'text',
    text: 'Company Name',
    enabled: true,
    x: 193,
    y: 159,
    align: 'left',
    fontFamily: 'SF Pro Display',
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000000',
    letterSpacing: 0,
    lineHeight: 1.2,
    textTransform: 'uppercase',
    shadow: false,
    shadowColor: '#000000',
    shadowBlur: 0,
    gradient: { enabled: false, startColor: '#ffffff', endColor: '#cccccc', type: 'vertical' },
    stroke: { enabled: false, color: '#000000', width: 1 },
    isDynamic: true,
    dynamicParam: 'member'
  },
  {
    id: 'location',
    name: 'Location',
    type: 'text',
    text: 'City | State',
    enabled: true,
    x: 193,
    y: 174,
    align: 'left',
    fontFamily: 'SF Pro Text',
    fontSize: 12,
    fontWeight: 'normal',
    color: '#434343',
    letterSpacing: 0,
    lineHeight: 1.2,
    textTransform: 'none',
    shadow: false,
    shadowColor: '#000000',
    shadowBlur: 0,
    gradient: { enabled: false, startColor: '#ffffff', endColor: '#cccccc', type: 'vertical' },
    stroke: { enabled: false, color: '#000000', width: 1 },
    isDynamic: true,
    dynamicParam: 'location'
  },
  {
    id: 'rating',
    name: 'Rating',
    type: 'text',
    text: 'A',
    enabled: true,
    x: 262,
    y: 131,
    align: 'left',
    fontFamily: 'SF Pro Display',
    fontSize: 46,
    fontWeight: '900',
    color: '#2C1818',
    letterSpacing: 1,
    lineHeight: 1.2,
    textTransform: 'none',
    shadow: false,
    shadowColor: 'rgba(0,0,0,0.5)',
    shadowBlur: 0,
    gradient: { enabled: true, startColor: '#FFFFFF', endColor: '#C9A872', type: 'vertical' },
    stroke: { enabled: false, color: '#000000', width: 1 },
    isDynamic: true,
    dynamicParam: 'rating'
  },
  {
    id: 'plan',
    name: 'Plan (Legacy)',
    type: 'text',
    text: '',
    enabled: false,
    x: -1000,
    y: -1000,
    align: 'left',
    fontFamily: 'Helvetica',
    fontSize: 1,
    fontWeight: 'normal',
    color: 'transparent',
    letterSpacing: 0,
    lineHeight: 1,
    textTransform: 'none',
    shadow: false,
    shadowColor: '#000000',
    shadowBlur: 0,
    gradient: { enabled: false, startColor: '#ffffff', endColor: '#cccccc', type: 'vertical' },
    stroke: { enabled: false, color: '#000000', width: 1 },
    isDynamic: false
  }
];

export const DEFAULT_TEMPLATES: Template[] = [
  {
    id: 'standard-member',
    name: 'Standard Member',
    description: 'Professional verification badge',
    badge: 'STD',
    accentColor: 'from-yellow-500 to-yellow-700',
    status: 'active',
    imageUrl: 'https://restorationexpertise.com/wp-content/uploads/2025/11/badge_notext_full.webp',
    layers: {
      'header': {
        x: 193,
        y: 97,
        fontFamily: 'SF Pro Display',
        fontSize: 16,
        fontWeight: '900',
        color: '#000000',
        align: 'left',
        shadow: false,
        letterSpacing: 0,
        textTransform: 'uppercase',
        gradient: { enabled: false, startColor: '#ffffff', endColor: '#000000', type: 'vertical' },
        stroke: { enabled: false, color: '#000000', width: 1 }
      },
      'member-name': {
        x: 193,
        y: 159,
        fontFamily: 'SF Pro Display',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#000000',
        align: 'left',
        shadow: false,
        letterSpacing: 0,
        textTransform: 'uppercase',
        gradient: { enabled: false, startColor: '#ffffff', endColor: '#000000', type: 'vertical' },
        stroke: { enabled: false, color: '#000000', width: 1 }
      },
      'location': {
        x: 193,
        y: 174,
        fontFamily: 'SF Pro Text',
        fontSize: 12,
        fontWeight: 'normal',
        color: '#434343',
        align: 'left',
        shadow: false,
        letterSpacing: 0,
        textTransform: 'none',
        gradient: { enabled: false, startColor: '#ffffff', endColor: '#000000', type: 'vertical' },
        stroke: { enabled: false, color: '#000000', width: 1 }
      },
      'rating': {
        x: 262,
        y: 131,
        fontFamily: 'SF Pro Display',
        fontSize: 46,
        fontWeight: '900',
        color: '#2C1818',
        align: 'left',
        shadow: false,
        letterSpacing: 1,
        textTransform: 'none',
        gradient: { enabled: true, startColor: '#FFFFFF', endColor: '#C9A872', type: 'vertical' },
        stroke: { enabled: false, color: '#000000', width: 1 }
      },
      'plan': {
        x: -1000,
        y: -1000,
        text: '',
        fontFamily: 'Arial',
        fontSize: 1,
        fontWeight: 'normal',
        color: 'transparent',
        align: 'left',
        shadow: false
      }
    }
  },
  {
    id: 'founding-member',
    name: 'Founding Member',
    description: 'Exclusive early adopter badge',
    badge: 'FND',
    accentColor: 'from-slate-500 to-slate-700',
    status: 'active',
    imageUrl: 'https://restorationexpertise.com/wp-content/uploads/2025/11/founding_member_notext.webp',
    layers: {
      'header': {
        x: 193,
        y: 97,
        fontFamily: 'SF Pro Display',
        fontSize: 16,
        fontWeight: '900',
        color: '#000000',
        align: 'left',
        shadow: false,
        letterSpacing: 0,
        textTransform: 'uppercase',
        gradient: { enabled: false, startColor: '#ffffff', endColor: '#000000', type: 'vertical' },
        stroke: { enabled: false, color: '#000000', width: 1 }
      },
      'member-name': {
        x: 193,
        y: 159,
        fontFamily: 'SF Pro Display',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#000000',
        align: 'left',
        shadow: false,
        letterSpacing: 0,
        textTransform: 'uppercase',
        gradient: { enabled: false, startColor: '#ffffff', endColor: '#000000', type: 'vertical' },
        stroke: { enabled: false, color: '#000000', width: 1 }
      },
      'location': {
        x: 193,
        y: 174,
        fontFamily: 'SF Pro Text',
        fontSize: 12,
        fontWeight: 'normal',
        color: '#434343',
        align: 'left',
        shadow: false,
        letterSpacing: 0,
        textTransform: 'none',
        gradient: { enabled: false, startColor: '#ffffff', endColor: '#000000', type: 'vertical' },
        stroke: { enabled: false, color: '#000000', width: 1 }
      },
      'rating': {
        x: 262,
        y: 131,
        fontFamily: 'SF Pro Display',
        fontSize: 46,
        fontWeight: '900',
        color: '#2C1818',
        align: 'left',
        shadow: false,
        letterSpacing: 1,
        textTransform: 'none',
        gradient: { enabled: true, startColor: '#FFFFFF', endColor: '#C9A872', type: 'vertical' },
        stroke: { enabled: false, color: '#000000', width: 1 }
      },
      'plan': {
        x: -1000,
        y: -1000,
        text: '',
        fontFamily: 'Arial',
        fontSize: 1,
        fontWeight: 'normal',
        color: 'transparent',
        align: 'left',
        shadow: false
      }
    }
  },
  {
    id: 'elite',
    name: 'Elite Professional (Legacy)',
    description: 'Gold badge style',
    badge: 'A+',
    accentColor: 'from-yellow-400 to-yellow-600',
    layers: {
      'header': {
        text: 'Elite Restoration Professional',
        x: 860,
        y: 340,
        fontFamily: 'SF Pro Display',
        fontSize: 11,
        fontWeight: '900',
        color: '#2C1810',
        align: 'center',
        shadow: true,
        letterSpacing: 1,
        textTransform: 'uppercase'
      },
      'member-name': {
        x: 276,
        y: 160,
        fontFamily: 'SF Pro Display',
        fontSize: 14,
        fontWeight: '900',
        color: '#000000',
        align: 'left',
        shadow: true
      },
      'location': {
        x: 276,
        y: 185,
        fontFamily: 'SF Pro Text',
        fontSize: 12,
        fontWeight: 'normal',
        color: '#4a4a4a',
        align: 'left',
        shadow: false
      },
      'plan': {
        text: 'Gold',
        x: 267,
        y: 175,
        fontFamily: 'SF Pro Display',
        fontSize: 14,
        fontWeight: '900',
        color: '#B8860B',
        align: 'left',
        shadow: false
      },
      'rating': {
        text: 'A+',
        x: 935,
        y: 368,
        fontFamily: 'SF Pro Display',
        fontSize: 48,
        fontWeight: '900',
        color: '#2C1810',
        align: 'center',
        shadow: true,
        gradient: { enabled: true, startColor: '#F4E5D3', endColor: '#C9A961', type: 'vertical' }
      }
    }
  }
];
